version: '3'

services:
    fontend:
        expose:
            - '8080'
        environment:
            - VIRTUAL_HOST=buiomalum.com
            - LETSENCRYPT_HOST=buiomalum.com
            - LETSENCRYPT_EMAIL=zhl146@gmail.com
        restart: always

networks:
    default:
        external:
            name: nginx-proxy
